SELECT fp.PRODUCT_ID, PRODUCT_NAME, (SUM_AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS fp
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '220501' AND '220531'
    GROUP BY PRODUCT_ID
) AS fo
ON fp.PRODUCT_ID = fo.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID