SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM SKILLCODES s JOIN DEVELOPERS d
WHERE d.SKILL_CODE & (
    SELECT SUM(CODE) 
    FROM SKILLCODES 
    WHERE CATEGORY = 'Front End')
ORDER BY d.ID