WITH tmp AS (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
)
SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT ui.USER_ID) AS USERS
FROM tmp JOIN USER_INFO ui ON tmp.USER_ID = ui.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER