SELECT i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO as i join REST_REVIEW as r ON i.REST_ID = r.REST_ID
GROUP BY i.REST_ID
HAVING ADDRESS like '서울%'
ORDER BY SCORE DESC, FAVORITES DESC