WITH f AS (
    SELECT NAME
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT
    CASE 
        WHEN (d.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN (SELECT NAME FROM f))) > 0
             AND (d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0 THEN 'A'
        WHEN (d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0 THEN 'B'
        WHEN (d.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN (SELECT NAME FROM f))) > 0 THEN 'C'
        ELSE NULL
    END AS GRADE,
    d.ID, d.EMAIL
FROM 
    DEVELOPERS d
WHERE 
    (d.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN (SELECT NAME FROM f))) > 0
    OR (d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0
ORDER BY 
    GRADE, d.ID;
