SELECT FLAVOR
FROM (
    SELECT 
        f.FLAVOR, 
        f.TOTAL_ORDER + SUM(j.TOTAL_ORDER) AS TOTAL_ORDER_SUM
    FROM 
        FIRST_HALF f
    LEFT JOIN 
        JULY j ON f.FLAVOR = j.FLAVOR
    GROUP BY 
        f.FLAVOR, f.TOTAL_ORDER
) AS CombinedOrders
ORDER BY 
    TOTAL_ORDER_SUM DESC
LIMIT 3;