-- 코드를 입력하세요
WITH ugb AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING 700000 <= TOTAL_SALES
)
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM ugb JOIN USED_GOODS_USER ugu ON ugb.WRITER_ID = ugu.USER_ID
ORDER BY TOTAL_SALES