SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS ED
JOIN 
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR) MS
    ON YEAR(ED.DIFFERENTIATION_DATE) = MS.YEAR
ORDER BY YEAR, YEAR_DEV